[project]
name = "discord-downloader"
version = "0.1.0"
description = "download discord chat logs"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "discord-py-self>=2.0.1",
    "zstandard>=0.23.0",
]
